### ISSUE TITLE
Cannot find module 'rrule'

### ISSUE THREAD

**Issue by sysmat** [naimo84/kalender-events#2]
**Describe the bug**
I try simple sample from readme and got error

**To Reproduce**
1. input
2. config
3. ouput

```typescript
import { KalenderEvents } from "kalender-events";

const ev = new KalenderEvents({
    url: "https://****",
    type: "caldav",
    username: "****",
    password: "****"
});

export const fetchEvents = (): void => {
    ev.getEvents({
        type: "caldav",
        preview: 10,
        previewUnits: 'days',
        pastview: 10,
        pastviewUnits: 'days'
    }).then(data => {
        console.log(data);
    });
}

```
**Expected behavior**
With npm lib as node-caldav-mod it work fine 

**Screenshots**
```
Cannot find module 'rrule' from 'node_modules/kalender-events/node_modules/node-ical/ical.js'

    Require stack:
      node_modules/kalender-events/node_modules/node-ical/ical.js
      node_modules/kalender-events/node_modules/node-ical/index.js
      node_modules/kalender-events/dist/caldav.js
      node_modules/kalender-events/dist/lib.js

```
**node-red-contrib-ical-events
 - Version [e.g. 0.1.22]
 - node-red version
 - nodejs version: v12.6.0

**Additional context**

**Comment by naimo84** [comment]
Hi sysmat,

unfortunately the newest rrule 2.6.5 is broken. Which comes through the dependencies of node-ical.
![image](https://user-images.githubusercontent.com/11535502/91535344-4d5fdd00-e913-11ea-9ed7-ed85bddef140.png)


I will deploy a fix, where i set it to 2.6.4.

Sorry and kind regards,
Benjamin
