### ISSUE TITLE
Bump to version 0.22.1

### ISSUE THREAD

**Issue by fflorent** [naimo84/kalender-events#7]
I would appreciate a new minor release embedding the fix #6 as I depend on it. Also same for [nodered-contrib-ical-events](https://flows.nodered.org/node/node-red-contrib-ical-events)).

No hurry though, as you seem to be a bit busy currently I can import the patch manually in the node_modules :).

**Comment by naimo84** [comment]
Hi @fflorent,

both versions are bumped 😉 even with less time, this is no big deal 😂

Greets,
Benjamin

**Comment by fflorent** [comment]
Thanks a lot Benjamin !

23 déc. 2021 08:19:26 Benjamin ***@***.***>:

**Comment by naimo84** [comment]
Your are crazy 👍 Thanks for the ko-fi 🥳 🎉

**Comment by naimo84** [comment]
I try to implement a Backers List in the readme. Would you mind, to mention you in this list?

**Comment by fflorent** [comment]
I ask nothing in return, I think this kind of little retribution is something I owe you.
Feel free to mention me or not.

Merry Christmas :)
