### ISSUE TITLE
[BUG]: event sensor does not output anything in the description

### ISSUE THREAD

**Issue by rallep71** [naimo84/kalender-events#8]
until the update, i always used the description in the calendar to pass values, for example: (open, close,) (on , off) (10, 5, (degree)).

i cant use msg.payload.description.(value)

this is no longer possible, why?

MfG

**Comment by naimo84** [comment]
Hi @rallep71 ,

sorry for any inconveniences... this is not intended. The description should be there.

Could you please provide me some more informations?
Is it a ical, caldav or icloud calendar?

 The flow-json would be interesting also.

Greets,
Benjamin

**Comment by naimo84** [comment]
I did a quick test on all 3 types. Currently I don't see the error. So more informations will be useful :)

**Comment by naimo84** [comment]
Closed due to missing additional informations. 

Greets,
Benjamin
