### ISSUE TITLE
[BUG]: Filtering on event data with language like summary is not possible

### ISSUE THREAD

**Issue by CDaxi** [naimo84/kalender-events#9]
**Describe the bug**

**To Reproduce**
Use for example this calendar:
https://abfuhrtermine.awp-paf.de/WasteManagementPfaffenhofen/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=165472001&AboID=284378&Fra=RM;B;P;S

It contains for example `SUMMARY;LANGUAGE=de:Restmuell ` or `DESCRIPTION;LANGUAGE=de:Bitte stellen Sie die Behälter bis 6:00 Uhr zur Abholung bereit.`.

If you configure the filterProperty to "summary", the summary attribute contains an object like:
```
{
 "params": {
  "LANGUAGE": "de"
 },
 "val": "Restmuell "
}
```

This is the reason why the regex filter can not work, it is no string, it is an object.

**Expected behavior**
If the property is an object and contains a key "val", use this attribute for filtering.

https://github.com/naimo84/kalender-events/blob/e1860207391784a68c25d3fbe13787f0ba7324b3/src/lib.ts#L438-L446
can be changed to something like:
```
            if (Array.isArray(filterProperty)) {
                for (const prop of filterProperty) {
                    if (regex.test(prop)) {
                        return true;
                    }
                }
            } else if (typeof filterProperty === 'object' && 'val' in filterProperty) {
                return regex.test(filterProperty.val);
            } else {
                return regex.test(filterProperty);
            }
```

This code is not tested, but should work.

The issue was found while using node-red-contrib-ical-events.
<img width="489" alt="Bildschirmfoto 2022-06-05 um 10 43 52" src="https://user-images.githubusercontent.com/2583954/172042741-ff422149-f76d-4b08-9ff7-660ba88c6c8d.png">

**Comment by naimo84** [comment]
Fixed with [v0.28.1](https://github.com/naimo84/kalender-events/releases/tag/v0.28.1)
